POST http://localhost:8080/api/user/registered?certificate=123
Content-Type: application/json

{
  "userName": "dhz",
  "mobile": "19886834468",
  "mobileBindTime": null,
  "email": "2335073254@qq.com"
}

###
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "identifier": "123",
  "certificate": "123"
}

###


POST http://localhost:8080/test2/test4
Content-Type: application/json

{
  "user": {
    "id": 123,
    "gmtCreate": null,
    "gmtModified": null,
    "userId": null,
    "registerSource": null,
    "userName": "dhz",
    "mobile": "1231",
    "mobileBindTime": null,
    "email": "200@qq.com",
    "emailBindTime": null,
    "birthday": null,
    "gender": null,
    "headPortrait": null,
    "status": null
  },
  "us": {
    "id": null,
    "gmtCreate": null,
    "gmtModified": null,
    "userId": null,
    "identityType": null,
    "identifier": null,
    "certificate": null,
    "isValid": null
  }
}

###
GET http://localhost:8080/test2/test3





###
http://localhost:8080/test2/test2



