server:
  port: 8080
  netty:
    connection-timeout: 60000

  servlet:
    multipart:
      enabled: true # 启用文件上传
      #      location: G:\2022spring\网络编程实践\thegodisgad\upload\temp
      max-file-size: 500MB # 单个文件上传最大大小限制
      max-request-size: 200MB # 单次请求主体最大大小限制
  acceptCount: 500
spring:

  mvc:
    format:
      date: yyyy-MM-dd # 日期格式
      date-time: yyyy-MM-dd HH:mm:ss # 日期时间格式
      time: HH:mm:ss # 时间格式
  messages:
    encoding: UTF-8
    basename: i18n/message
  datasource:
    url: jdbc:mysql://localhost:3306/thegodisgad?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root        #用户名
    password: thegodisgad #密码
    driver-class-name: com.mysql.cj.jdbc.Driver #
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML
    enabled: true
  main:
    allow-bean-definition-overriding: true
  aop:
    auto: true

## mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml     #扫描mybatis的实现dao接口*.xml文件
  type-aliases-package: top.thegodisgad.*.entity #实体类取别名
  global-config:
    refresh-mapper: true
    #驼峰下划线转换
    column-underline: true
  configuration:
    ## 下划线转驼峰配置
    map-underscore-to-camel-case: true
  spring:
    redis:
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce:
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-wait: -1
      # 连接池中的最大空闲连接 默认 8
      max-idle: 8
      # 连接池中的最小空闲连接 默认 0
      min-idle: 0

